#include "callpath_module.h"
#include <mpi.h>

/* Autogenerated wrapper code */
{{forallfn fn_name MPI_Finalize MPI_Wtime MPI_Finalized}}
{{retType}} {{fn_name}}{{argTypeList}}
{
  set_callpath();
  return P{{fn_name}}{{argList}};
}
{{endforallfn}}


